.docker-login: &docker-login
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY

.docker-logout: &docker-logout
    - docker logout $CI_REGISTRY

# Register la dernière image de main
algolia:search:index:
    image: docker:18.09.7-dind
    stage: indexation
    services:
        - docker:18.09.7-dind
    variables:
        ALGOLIA_APP_ID: 'ZV7NSE3BF9'
        ALGOLIA_API_KEY: '72cbda1599ca44ddbd1b62735d0b54c5'
    before_script:
        - *docker-logout
        - *docker-login
        - apk update
        - apk upgrade
        - apk add jq
    script:
        - docker run -e ALGOLIA_APP_ID="${ALGOLIA_APP_ID}" -e ALGOLIA_API_KEY="${ALGOLIA_API_KEY}" -e "CONFIG=$(cat ./algolia.config.json | jq -r tostring)" algolia/docsearch-scraper
    after_script:
        - *docker-logout
    only:
        - main
