.docker-login: &docker-login
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY

.docker-logout: &docker-logout
    - docker logout $CI_REGISTRY

# Register la dernière image de main
image:latest:register:
    image: docker:18.09.7-dind
    stage: register
    services:
        - docker:18.09.7-dind
    variables:
        ENVIRONMENT: 'production'
        VERSION: $CI_COMMIT_TAG
        IMAGE_TAG: 'latest'
    environment:
        name: $ENVIRONMENT
    resource_group: $ENVIRONMENT
    before_script:
        - *docker-logout
        - *docker-login
        - apk update
        - apk upgrade
        - apk add bash curl jq
        - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
    script:
        - >
            docker build
            --target serve
            --build-arg NODE_ENV=$ENVIRONMENT
            --pull
            --file "Dockerfile"
            --label "org.opencontainers.image.title=$CI_PROJECT_TITLE"
            --label "org.opencontainers.image.url=$CI_PROJECT_URL"
            --label "org.opencontainers.image.created=$CI_JOB_STARTED_AT"
            --label "org.opencontainers.image.revision=$CI_COMMIT_SHA"
            --label "org.opencontainers.image.version=$VERSION"
            --tag $CI_REGISTRY_IMAGE:$IMAGE_TAG
            .
        - docker push $CI_REGISTRY_IMAGE:$IMAGE_TAG
        - docker run -e ALGOLIA_APP_ID="ZV7NSE3BF9" -e ALGOLIA_API_KEY="72cbda1599ca44ddbd1b62735d0b54c5" -e "CONFIG=$(cat ./algolia.config.json | jq -r tostring)" algolia/docsearch-scraper
    after_script:
        - *docker-logout
    only:
        - main
